Repository UCLALibrary/libraryweb-site, pull requests merged in 2018-04, with the labels that each got.

#446 WS-960n: fixes token check logic
  www/sites/all/modules/custom/statsform/statsform.module
  www/sites/all/modules/custom/statsform/templates/page--hijacked.tpl.php
  www/sites/all/modules/custom/statsform/templates/page--hijackedLogin.tpl.php
Labels: enhancement

#447 fixed submit button disable on Research Assistance; updated labels
  www/sites/all/modules/custom/statsform/templates/page--hijacked.tpl.php
  www/sites/all/modules/custom/statsform/templates/page--hijackedLogin.tpl.php
Labels: enhancement, in progress

#448 WS-960p - updated label on popup
  www/sites/all/modules/custom/statsform/templates/page--hijackedLogin.tpl.php
Labels: enhancement, in progress

#452 DRUP-1274: removes manualcrop_media_wysiwyg requirement
  www/sites/all/modules/features/uclalib_media/uclalib_media.info
Labels: in progress

#453 DRUP-1274: Adds permissions for Media WYSIWYG: Use Media WYSIWYG in an editor
  www/sites/all/modules/features/uclalib_users/uclalib_users.features.user_permission.inc
  www/sites/all/modules/features/uclalib_users/uclalib_users.info
Labels: in progress

#455 DRUP-1276: adds module_missing_message_fixer module to clean up some missig modules
  www/sites/all/modules/contrib/module_missing_message_fixer/LICENSE.txt
  www/sites/all/modules/contrib/module_missing_message_fixer/README.txt
  www/sites/all/modules/contrib/module_missing_message_fixer/includes/module_missing_message_fixer.admin.inc
  www/sites/all/modules/contrib/module_missing_message_fixer/includes/module_missing_message_fixer.drush.inc
  www/sites/all/modules/contrib/module_missing_message_fixer/module_missing_message_fixer.info
  www/sites/all/modules/contrib/module_missing_message_fixer/module_missing_message_fixer.module
Labels: in progress

#456 DRUP-1276: adds module_missing_message_fixer module to clean up some missig modules
  www/sites/all/modules/contrib/module_missing_message_fixer/LICENSE.txt
  www/sites/all/modules/contrib/module_missing_message_fixer/README.txt
  www/sites/all/modules/contrib/module_missing_message_fixer/includes/module_missing_message_fixer.admin.inc
  www/sites/all/modules/contrib/module_missing_message_fixer/includes/module_missing_message_fixer.drush.inc
  www/sites/all/modules/contrib/module_missing_message_fixer/module_missing_message_fixer.info
  www/sites/all/modules/contrib/module_missing_message_fixer/module_missing_message_fixer.module
Labels: in progress

#457 DRUP-1278: Updates references_dialog from 7.x-1.0-alpha4+11-dev to 7.x-1.0-beta2
  www/PATCHES.txt
  www/sites/all/modules/contrib/references_dialog/css/references-dialog-admin.css
  www/sites/all/modules/contrib/references_dialog/js/references-dialog.js
  www/sites/all/modules/contrib/references_dialog/references_dialog.dialog_widgets.inc
  www/sites/all/modules/contrib/references_dialog/references_dialog.info
  www/sites/all/modules/contrib/references_dialog/references_dialog.module
Labels: in progress
